### ISSUE TITLE
add lateral window

### ISSUE THREAD

**Issue by ghost** [akiritsu/pRoJEct-VeXEd#7]
Hi again man,

I resolved the real time attack map with 
```html
<iframe src="https://cybermap.kaspersky.com/" width="2000" height="670"></iframe>
```
now it looks cool, only one problem: I would like to add lateral pop-up window with the same style of the site itself, 
do you know how could I accomplish that? 

Regards,

Edoardo Mantovani, 2020

**Comment by gmkzwwg** [comment]
Happy new year!
One choice is try to implement a brand new window by imitating:

/src/_includes/collection_list.html: HTML code and Jekyll code of the "Archive" popup window
/src/_sass/components: Style file of "Archive"

There are some steps:
1. Add a new .html file in /src/_includes and a new .scss file in /src/_sass/components
2.  Include the new .html file in /src/_layout/default.html, include the new .scss file in /src/_sass./_black_n_green.scss
3. Try to implement the popup window in your mind with a div element

If you need further help, please feel free to contact me.

**Comment by ghost** [comment]
Hi man,
Sorry for the late reply, but in those days I've tried to write a decent pop up..
unfortunately web isn't my "space" (I prefer C to Javascript & co).

How would you go about adapting the colors(& the size)  of the pop-up to those of the site? 
(link: https://baseband-processor.github.io/WirelessLegacy.github.io/)

Regards,

Ah, Happy new year!

**Comment by ghost** [comment]
Hi man again and sorry, I forgot to post the code:

(window.html)
```html

</head>
<body>

<button class="open-button" onclick="openForm()">About the Author</button>

<div class="form-popup" id="whoami">
</div>

</body>
</html>

```

(_window.css)
```css
.open-button {
  background-color: #555;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  opacity: 0.8;
  position: fixed;
  bottom: 23px;
  right: 28px;
  width: 280px;
}

/* The popup form - hidden by default */
.form-popup {
  display: none;
  position: fixed;
  bottom: 0;
  right: 15px;
  border: 3px solid #f1f1f1;
  z-index: 9;
}

/* Add styles to the form container */
.form-container {
  max-width: 300px;
  padding: 10px;
  background-color: white;
}

/* Full-width input fields */
.form-container input[type=text], .form-container input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background: #f1f1f1;
}

/* When the inputs get focus, do something */
.form-container input[type=text]:focus, .form-container input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit/login button */
.form-container .btn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  margin-bottom:10px;
  opacity: 0.8;
}

/* Add a red background color to the cancel button */
.form-container .cancel {
  background-color: red;
}

/* Add some hover effects to buttons */
.form-container .btn:hover, .open-button:hover {
  opacity: 1;
}
```
